package fs3.enums;

public enum HealthConditions {
    PROBLEMS_WITH_PERSONAL_CARE,
    PROBLEMS_WITH_DAILY_ACTIVITES,
    PROBLEMS_WITH_MOBILITY_AND_MOVEMENT,
    PROBLEMS_WITH_FLUID_INTAKE,
    PROBLEMS_WITH_FOOD_INTAKE,
    INAPPROPRIATE_WEIGHT_CHANGE,
    PROBLEMS_WITH_OBESITY,
    PROBLEMS_WITH_UNDERWEIGHT,
    PROBLEMS_WITH_SURGICAL_WOUNDS,
    PROBLEMS_WITH_DIABETIC_ULCERS,
    PROBLEMS_WITH_CANCEROUS_LESIONS;
}
